### ISSUE TITLE
Page to Blog Macro creates duplicate

### ISSUE THREAD

**Issue by erindelaneyb** [chris-kent/Confluence-Blog-Tools#12]
We have a Page Template which includes the Page To Blog macro. As of about a week ago, the Page To Blog macro is creating duplicates: one Blog Post and one Page. It's not an issue when the manual Convert To Blog option is used, but the macro is the essential functionality for us.

**Comment by erindelaneyb** [comment]
Further information: 

1. We are running Confluence 5.10.7 and 5.10.0 on our live and development instances, respectively. 

2. When the blog post is created via Page To Blog macro, whether via template or manually added to a page in edit mode, the page ID is added to the Blog Post title like so: "pagetoblog-9437335-test page to blog" is the title of the Blog Post when the entered title was "test page to blog".

These are serious issues for us.

**Comment by chris-kent** [comment]
Hi there,

Hmmm, as you may have known, Atlassian broke the functionality that my plugin uses to do the conversion of pages to blogs via the templates in version 5.10.0.

It took me many weeks working with Atlassian to come up with a work around.

This workaround is slow and requires the browser and server to try and keep in sync.  I have had to do this using delays.  What could be happening here is in your environment, if you have slow network latency, then the timing between the browser and server will miss and cause the problems you are seeing.

Moving forward, Atlassian have fixed this in 6.0, so if you intend to upgrade soon, then the plugin will work just like it did before 5.10.0, and the side effect you are seeing will disappear.

If you do not plan to upgrade soon, I can offer a new version which you will be able to configure/extend the delays between polling from the browser to the server.  This will fix the problem but will obviously mean that the process will take longer. 

If you feel you need this change, I will implement this for you, please advise.

Thanks

KC Integrations team.

**Comment by chris-kent** [comment]
This has been fixed in version 3.4
