### ISSUE TITLE
Confluence 6.x support

### ISSUE THREAD

**Issue by grapherdity** [chris-kent/Confluence-Blog-Tools#13]
Hi Chris,

I just want to know if there are any plans for a Confluence 6> compatibility release?

Since we waited a while, now we are planning to upgrade to 6.0.2 soon. It would be nice having your add-on 'on board'. ;)

Thanks,
Peter

**Comment by chris-kent** [comment]
Hi Peter

Yes i have it ready. Just doing some final testing.  Atlassian broke my
functionality again with thier version 6 release. So i have had to write
new code again to work around it.

I hope to have it avail in the next 24 hours.

**Comment by grapherdity** [comment]
Hi Chris,

oh, dear. They did it again? Sounds horrible. :(

But it's good to know a new release isn't that far away. Actually there's no need to hurry from our side, we are planning to upgrade in 2 weeks at the earliest. But I assume we are not the only customers. ;)

Thank you very much and good luck.

Peter
