### ISSUE TITLE
Allow restrictions to be removed on "convert to blog"

### ISSUE THREAD

**Issue by thomykay** [chris-kent/Confluence-Blog-Tools#15]
We use pages for authoring pages, content reviews and publishing approvals. If the page is under a restricted page the resultng blog entry gets the restrictions of the restricted (parent) page. is is not intended. Can we have a sticky option in the "convert to blog" dialog to not have the restrictions on the blog post?

**Comment by chris-kent** [comment]
Hi,
I have implemented this for you, please watch out for the next release of the plugin 3.5
Cheers

**Comment by chris-kent** [comment]
Feature added to version 3.5
