### ISSUE TITLE
Allow to remove comments (inline and normal comments) on convert to blog

### ISSUE THREAD

**Issue by thomykay** [chris-kent/Confluence-Blog-Tools#16]
During the review process on pages comments are made in context of the pages. These comments (inline and default) are still on the blog post after "convert to blog". Not our expected result.

Can we have a (sticky) option to remove the all comments on "convert to blog"?

**Comment by chris-kent** [comment]
Hi,
I have implemented this for you, please watch out for the next release of the plugin 3.5
Cheers

**Comment by chris-kent** [comment]
Feature added to version 3.5
