### ISSUE TITLE
"Convert Page to Blog Post" action deletes the metadata set of a page

### ISSUE THREAD

**Issue by maximilianpeter** [chris-kent/Confluence-Blog-Tools#17]
Hi Chris,

I don't know how to open the issue https://github.com/chris-kent/Confluence-Blog-Tools/issues/7 again. Hope it's OK to open a new one. 

We updatet to 3.4 with Confluence 5.10.8 and have the same issue again:

> When we convert a page into a blog post, unfortunately the metadata information from the page are not copied to the blog post.

Unfortunately we have another problem with the Blog Post Macro. When we create a page by using the confluence macro "Create page from template" and the template has the Blog Post Macro on it, the new site is still created as a childpage not as a blog-post.

Greets Max

**Comment by maximilianpeter** [comment]
And now we get this message: 
![image](https://cloud.githubusercontent.com/assets/20044167/22643734/1135faa2-ec60-11e6-999b-a8fc80ab808c.png)

**Comment by chris-kent** [comment]
Hi Max,

Hmmm, So it looks like you have 3 issues....

1. License Error
2. Blog macro not creating POST
3. Metadata integration is not working

This is not good, and I will have to debug this with your specific
versions.  Did this all start to occur after you upgraded either Blog Tools
plugin or the Confluence version?

I have had issues with Atlassian, I have 3 implementations, one for pre
5.10.0, one for 5.10.x, and another for 6+, since they re-designed they way
they create content, in 5.10, and then they modified this again for 6.0.

Anyway, I will look and see what is going wrong.  Please provide me
Confluence logs of the License Error, this is interesting and in the log I
hope the cause for the license error is provided - this will help me.

Thanks
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,
thanks for your quick reply.

The issue 1 isn't a permanent issue. Sometimes we get this message, sometimes not. I created to Log-Files. Log-File Nr. 1 contains the action "blog macro not creating post". The Log-File Nr. 2 was recorded during the "Convert Site to Blog Post" actio.

[Log-File-Nr1.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/757815/Log-File-Nr1.txt)
[Log-File-Nr2.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/757814/Log-File-Nr2.txt)

I created the Log-File Nr.1 and noticed the following behavior:

When I create a new site (Title: Test123) from a template with the "blog post macro" on it, the site is created in the navigation tree as a normal site. But this site won't shown after the saving process. After the creating-action the view changes to the blog.

If I try the creation with template a second time (Title: Test1234), the page from the previous creation action (Test123) will be moved to the blog and is shown as a blog post. The "Test1234" site is created as a normal site in den navigation. If I try it a third... time, it happens again with the last site before.

Greets Max

**Comment by chris-kent** [comment]
Hi Max,

Yes I know exactly what is going on here. I hope to have a fix for all the
issues mentioned...

Thanks for your patience, I'll let you know when I have posted the next
version

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hello Chris, 
we would like to update on 19.02.2017 to the version 5.10.8. What do you think? Do you have a solution for the issue in the next days?
Greets Max

**Comment by chris-kent** [comment]
Hi Max,

Yes I do hope to have it working in the next few days.

Cheers
Chris

**Comment by chris-kent** [comment]
Hi Max,
I have fixed the macro, I am not sure why the License Error is being shown, but I have extra logging to understand why this occurs to help me fix it in the future.

wrt the Metadata plugin, I'm not sure why this no longer works, I have tried 2 other methods to detect the plugin, as I need to optionally use the API, nothing is working in 5.10.8. I may have to resort to asking Atlassian for help.

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,
this is a problem for us and we hope you will find a resolution for this issue.
Greets Max

**Comment by chris-kent** [comment]
Hi Max,

All, done, please try version 3.5 and let me know how it goes...

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,
the problems 2 and 3 are resolved. But the licence error already exists. If I try to create a blog for the first time with create from template macro, i get the licence error and the site is created as a page in the navigation tree. If I try it a second, third.... time it works fine.
Greets Max

**Comment by maximilianpeter** [comment]
Hey Chris, this was an error with our base URL. We fixed it and know it works fine. Thanks for your quick help!!!

**Comment by maximilianpeter** [comment]
Hi Chris,

I've wanted to let you know that [Metadata 3.0 released last week](https://www.communardo.com/metadata-confluence-3-0/), and with it, the new feature "Copy the Metadata when copying / moving a Confluence Page".

This possibly solves the initial cause raised in this issue, don't you think? If that's the case, you could remove that functionality from the plugin and save yourself the trouble of maintaining the Metadata API.

Maybe you have the time to test and verify this? We would be happy to help you out, too :)

Cheers 
Max
