### ISSUE TITLE
Invalid license error message

### ISSUE THREAD

**Issue by mmilone** [chris-kent/Confluence-Blog-Tools#18]
Hello, a few days ago we upgraded to v3.5 and now, when we try to move pages to blog posts and vice verse, we get the error message "This plugin has an invalid license.
I have checked the add-on the the license is valid. We are running Confluence Server 6.0.2.
Please advise. Thanks.

**Comment by chris-kent** [comment]
Hi there.

Can you please turn on logging for the Plugin. Add the key net.kentcom for
ALL then execute the functions. The confluence log file should have details
as to why this is hapenning.

Please send to me the log file or at least the lines with net.kentcom.

As a suggestion. Please check you r general settings for the confluence
base url. Another customer had this problem and found this was incorrectly
set.

Cheers
Chris

**Comment by mmilone** [comment]
Hi Chris,
Weirdly, this is now working!?
I will follow your advise if it re-occurs.
Thanks,
Marco

**Comment by chris-kent** [comment]
Hi 
Can I close this issue?
Cheers

**Comment by mmilone** [comment]
Yes, thanks.
