### ISSUE TITLE
"Page to Blog" doesn't work with special characters

### ISSUE THREAD

**Issue by maximilianpeter** [chris-kent/Confluence-Blog-Tools#19]
Hello Chris,

we have a big problem in our prod environment, since we have updated to version 3.5 last week. Whenever we try to create a blog-post by using a site-template (with Page to Blog-Macro) and the title contains special characters like  ".:;!"§$%&/()=? and so on", it doesn't work. In case we try to save the page, the action loads and loads and loads and nothing happens. If we abort the saving process by closing the site, the page is created in the navigation tree. If we delete the macro "Page to Blog" it works fine. If we try it with the "convert to blog" action it works also fine. 

Do you have any idea? It's a high priority issue for us, because all our users have this problem.

Greets Max

**Comment by chris-kent** [comment]
Hi Max,

You are truly the biggest user of my plugin, and great tester :)

I see exactly the problem, I just need to handle pages that don't support
text name url's, which has now been exposed due to the new API's I use.

Hopefully I will have a fix in the next day or 2...

Cheers
Chris

**Comment by chris-kent** [comment]
This has been fixed

Cheers
Chris

**Comment by maximilianpeter** [comment]
Everything works fine now. Thanks a lot and a nice day.
