### ISSUE TITLE
page template with page to blog add image issue

### ISSUE THREAD

**Issue by aydavidc** [chris-kent/Confluence-Blog-Tools#2]
We have a page template that includes the page to blog macro. When a user creates the page with the template and drops a image to the page and tries to save it they see this message:

The page you were trying to reach could not be found. This could be because:

    The page does not exist.
    The page exists, but you do not have permission to view it.

We have no issues when the user just adds text

Also if we remove the page to blog macro the issue goes away.

We are using confluence 5.8.4 and Confluence blog tools 2.2.1

**Comment by chris-kent** [comment]
Hi,

Thanks for the feedback, I will be looking into this and hopefully have an update for you soon.

Cheers
Chris

**Comment by chris-kent** [comment]
This has been fixed in version 2.3
