### ISSUE TITLE
"Page to Blog" doesn't work with double point

### ISSUE THREAD

**Issue by maximilianpeter** [chris-kent/Confluence-Blog-Tools#20]
Hey Chris, we have this issue (https://github.com/chris-kent/Confluence-Blog-Tools/issues/19) again with double Points. May you check this please :-)?

Greets Max

**Comment by chris-kent** [comment]
Hi Max,

I am testing this now and can't repeat this issue, some of my test titles
include "My.page"  "my..page" "my.page.2..."

Can you send me some page titles examples that do not work...

Cheers
Chris

**Comment by chris-kent** [comment]
Hi Max,

I was thinking about this and thought maybe you meant a colon ":", and after testing I can reproduce the problem (Atlassian are not consistent - ahhh).

Anyway, I should have a fix soon.

Cheers
Chris

**Comment by chris-kent** [comment]
Hi Max, 
This has been fixed, please try ver 3.7
Cheers

**Comment by maximilianpeter** [comment]
Sorry Chris, I have used the wrong word. Now it works fine. Greets Max
