### ISSUE TITLE
Security Issue when recieviving notifications

### ISSUE THREAD

**Issue by maximilianpeter** [chris-kent/Confluence-Blog-Tools#21]
Hi, 

we encountered a problem when someone is subcribed to a space where a new blogpost is written. In the notification email, which this user receives are posts visible, even when this user has no permission to view the page created and converted to a blog post. When the user clicks the link in the mail, everything works fine and the user gets a "no permission". But the security issue is, that the user can see the full content of a page in the notification email, where he has no permission on. 

Can you confirm this issue and can you solve it?

Greetings Max

**Comment by chris-kent** [comment]
Hi Max,

This is interesting, as I don't do anything with the notifications, this just happens as per standard Confluence behavior. 

Does this behavior occur on normal pages created from a template that has page restrictions? I don't have an email notification system setup on my development area, so this is hard for me to test.

Cheers
Chris

**Comment by chris-kent** [comment]
Hi Max,

I have not looked at this.  Is this critical and is this behaviour different from how other templates work?

I am doing work on another plugin, but if I get some spare time, I may play around and see what I can make of this security issue.

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,
currently we are running some internal tests to reproduce the issue again and to find out, whether it is a confluence or an add-on problem. I will write a comment if we have more infos.

Greets Max

**Comment by chris-kent** [comment]
Hi Max,

Any luck with reproducing the issue with other (non-blog) templates?

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hi Chris, we have the same problem witout using blog-posts. I think it's no problem with your add-ons. Sorry for this.

Greets Max

**Comment by chris-kent** [comment]
Phew. I was looking at the code and wondering how i was going to fix this.
You should raise a high level security issue with atlassian about this
problem.

Cheers
Chris
