### ISSUE TITLE
Issues with drafts...

### ISSUE THREAD

**Issue by erindelaneyb** [chris-kent/Confluence-Blog-Tools#23]
One of our users just exposed something I hadn't noticed -- when using the Page To Blog macro on a Template, drafts can get a little messy. 

1. Setup Template with Page To Blog macro.
2. Create new Page using this Template. Close without saving. 
3. Open Drafts, locate draft of Page. Edit, save.
4. Page publishes as a Page, not as a Blog.

At this point we can of course manually convert the Page to a Blog but this would defeat the purpose of the macro. 

For reference's sake, I'm running Confluence 5.10.0 and Confluence Blog Tools 3.8.

Any ideas?

Thanks in advance.

**Comment by chris-kent** [comment]
Hi there,

The macro was not designed to work with Drafts, Nor Pages, only Templates.

However I can look into what it would take to work with macros and if possible I can try to implement.  The scenario you have outlined is an anomaly, I would not expect this to be normal behavior, Drafts typically only occur when there are network issues which prevent page Saves from occurring correctly.

I will see what it takes to address this scenario.

Cheers.

**Comment by erindelaneyb** [comment]
Hi Chris, 

Yes, unfortunately network issues are very common with our team, and so even with good connections, they have become accustomed to working with and relying on the autosave functionality.

Thank you for the work you've done, this add-on is integral for us.

**Comment by chris-kent** [comment]
Hi Erin,

I can have a solution for you, it is taking a while as the developer
environment for Confluence does not support Drafts, so I have to use a
shared Confluence site for testing which is slow to develop code against :(.

My next release will have a fix for this issue. I'll let you know when it
is released.

Cheers
Chris

**Comment by chris-kent** [comment]
Hi there,

This has been fixed and published, please grab version 3.9 and give it a try.

Cheers

**Comment by erindelaneyb** [comment]
Hi Chris, 

Thanks for this! It works beautifully!
