### ISSUE TITLE
German translation for Blog Tools

### ISSUE THREAD

**Issue by maximilianpeter** [chris-kent/Confluence-Blog-Tools#24]
Hey Chris,
may it possible to add a german language file? I would provide the translations for you.
Greets Max

**Comment by chris-kent** [comment]
Hi Max,

Sure, I have the properties file attached. If you can replace the string
values with German text (leave the keys in English), then I'll Bundle it
back into the next version.

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hey Chris,

there is no file attached. May you send me the file again per E-Mail to maximilian.peter@lvr.de<mailto:maximilian.peter@lvr.de>

Greets Max

Von: chris-kent [mailto:notifications@github.com]
Gesendet: Mittwoch, 26. April 2017 12:50
An: chris-kent/Confluence-Blog-Tools <Confluence-Blog-Tools@noreply.github.com>
Cc: Peter, Maximilian <Maximilian.Peter@lvr.de>; Author <author@noreply.github.com>
Betreff: Re: [chris-kent/Confluence-Blog-Tools] German translation for Blog Tools (#24)

Hi Max,

Sure, I have the properties file attached. If you can replace the string
values with German text (leave the keys in English), then I'll Bundle it
back into the next version.

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hey Chris, 

the add-on works well, but there are still problems with the german characters ß, ö, ä and ü. I have attached two screenshots.

![screen1](https://cloud.githubusercontent.com/assets/20044167/25521363/84611b68-2bff-11e7-847b-1564106f5849.jpg)
![screen2](https://cloud.githubusercontent.com/assets/20044167/25521364/846178ec-2bff-11e7-950a-fc3f69450ff4.jpg)

Greets Max

**Comment by maximilianpeter** [comment]
Hey Chris,
the new version doesn't solve the issue with the characters. Our developer had an idea to solve the problem and did same changes in the properties file. Now it works fine. The file is attached. 

[confluence-blog-tools_de_DE.properties.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/970211/confluence-blog-tools_de_DE.properties.txt)

Greets Max

**Comment by chris-kent** [comment]
Thanks, that is awesome.
I will publish the official version on the Market Place soon.

Cheers
Chris
