### ISSUE TITLE
Error in log-file while using Blog Tools

### ISSUE THREAD

**Issue by maximilianpeter** [chris-kent/Confluence-Blog-Tools#26]
Hey Chris,
whenever we use the blog post macro our log-file contains this errors. May you have a look about this issue?

Cheers
Max
[20170704error.zip](https://github.com/chris-kent/Confluence-Blog-Tools/files/1122502/20170704error.zip)

**Comment by chris-kent** [comment]
Hi Max,

Can you please grab another log file after enabling logging for net.kentcom
and send this to me

In this scenario, are you using a template (macro) or converting using the
Tools menu?

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,

sure, I've attached a new log file.
We create the blog post using a template which has the PageToBlog macro embedded and contains metadata.

Regards,
Max

[20170705error.log.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/1123855/20170705error.log.txt)

**Comment by chris-kent** [comment]
Hi Max,

I am not sure what has started to cause this, it is actually the metadata
plugin that is trying to remove it's links and throws the error when I
delete the original page.

Is the process fully working? I can see that the blog is created, but is
the original page removed?

If so, I can easily stop the exception, if the process is working
correctly, let me know and I should be able to resolve this easily.
If the original page is not being deleted, then I may have some extra work
to do -> nothing has changed in this area for a while...

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,

the process is indeed fully working as it should. The blog is created and the original page gets removed.
Would be great if the exception message could be eliminated.

Cheers
Max

**Comment by chris-kent** [comment]
Hi Max,

Can you please try the attached jar file.  Let me know if this resolves the issue, if so I'll put it on the market place.

Cheers
Chris
[confluence-blog-tools-3.13.jar.zip](https://github.com/chris-kent/Confluence-Blog-Tools/files/1124518/confluence-blog-tools-3.13.jar.zip)

**Comment by maximilianpeter** [comment]
Hi Chris,

thanks for the quick response.
Unfortunately, we still get the same error with this version.

Cheers 
Max

[20170705_02error.log.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/1124572/20170705_02error.log.txt)

**Comment by chris-kent** [comment]
Hi Max,

Unfortunately this has something to do with Metadata plugin, I'm not sure why this has started to occur, and I don't have a system to test this.

I have made a change, no idea if it fixes the exception trace, but please give it a try.

Cheers
Chris
[confluence-blog-tools-3.13.jar.zip](https://github.com/chris-kent/Confluence-Blog-Tools/files/1127638/confluence-blog-tools-3.13.jar.zip)

**Comment by maximilianpeter** [comment]
Hi Chris,

the error still persists with this version.
We have opened an issue report on the Metadata support site, maybe they have an idea about this.

Nevertheless, thanks for your efforts!

Cheers
Max

**Comment by chris-kent** [comment]
Hi Max,

Can you please add this code to the issue you raised with Communardo, it is
the code that copies their data from the template to the blog.  They might
then be able to shed some light on what has changed and how I can avoid the
Exception.


The Exception is being thrown when I call source.remove(..)

{code}

List<MetadataSet> sets = metadataManager.loadContentMetadataSets(source);

for (MetadataSet metadataset : sets) {

    metadataManager.saveContentMetadataSet(destination, metadataset);
    List<MetadataField> metadataFields = metadataset.getMetadataFields();

    for (MetadataField metadataField : metadataFields) {
        DataObject dataObject =
metadataManager.loadContentMetadataValue(source, metadataField);
        metadataManager.saveContentMetadataValue(destination,
metadataField, dataObject);
    }
}

source.remove(pageManager_m);

{code}

**Comment by chris-kent** [comment]
Hi Max,

Any feedback from Communardo?

Chris

**Comment by maximilianpeter** [comment]
Hi Chris,

unfortunately not. I looks like they need some time to analyze the issue :-).

Greets Max

**Comment by chris-kent** [comment]
Hmmm. Is there any possibility you can track down when the exceptions
started and if this corresponds to an update to either of the plugins?

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,
I'm afraid we can't as our log files don't reach back far enough.
If you have a clue which update may have introduced this issue, we could try installing an older version and test if it still happens?

**Comment by chris-kent** [comment]
Hi Max,

My suspicion is that this started to happen when I had to rework how the
plugin worked with templates from Conf ver 5.10.0 onwards.  I'll have
another look and see if I find something else to try.

Have you heard anymore from Communardo?

Cheers
Chris

**Comment by chris-kent** [comment]
Hi Max,

I have been communicating with Communardo on this issue (I have not forgotten about you my friend :)

Anyway, we uncovered a bug in their ad-on, and they are going to rectify this in their next version.  You may be able to see the issue here: https://jira.communardo.de/servicedesk/customer/portal/1/SUPPORT-8535

So, please keep an eye out for their next version and see if the issue goes away!

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,
thank you so much. Great service!
Cheers Max
