### ISSUE TITLE
User denied access to their own blog post

### ISSUE THREAD

**Issue by maximilianpeter** [chris-kent/Confluence-Blog-Tools#31]
Hi Chris,

we've updated our production site to the latest version of Blog Tools 3.15 (and Confluence 6.6.1).
Since then, several users face the following problem when using the Blog Tools macro in a specific setup:

1) User A and User B have full space permissions
2) User A creates a page and restricts it so only user A and B can edit/view
3) Now, User B creates a subpage below the first page.
4) User B views the subpage and selects "Convert page to blog". 
5) User B gets a "permission denied"-page because for some reason, the resulting blog post is restricted to User A only.

Do you have an idea? Unfortunately, this affects a lot of our users.
Maybe this stems from our previous "experiments" regarding Issue 27? https://github.com/chris-kent/Confluence-Blog-Tools/issues/27

Cheers,
 Max

**Comment by maximilianpeter** [comment]
Here's what happens in the log file:
[blogtools_1.log](https://github.com/chris-kent/Confluence-Blog-Tools/files/1895072/blogtools_1.log)

**Comment by maximilianpeter** [comment]
Hi Chris,

we can confirm that this issue does not occur with Blog Tools 3.14.
We have downgraded on our production site for now, please have a look at this.

Cheers
Max

**Comment by chris-kent** [comment]
Hi Max,

I will take a look, and get back to you. Might be another week however as I am working on another plugin right now.

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,

did you have a chance to look at this?
Using the previous version causes another issue where a notification for the wrong (deleted) page gets send.

Cheers
Max

**Comment by chris-kent** [comment]
Hi Max,

Hmmm, the short answer is yes, but unfortunately I am struggling with
getting the functionality to work. Atlassian is no help.
I think I have to redesign how the plugin works in order to use the
framework they introduced in version 5.10.

I am working on another plugin at the moment and hope to have a serious
look at the PageToBlog macro after that.

Cheers
Chris

**Comment by chris-kent** [comment]
Please install version 3.16, I believe this has now fixed the issue
