### ISSUE TITLE
Page to Blog Macro with Blueprints

### ISSUE THREAD

**Issue by janedag** [chris-kent/Confluence-Blog-Tools#33]
Hey,
we want to use your Blog Tools for Confluence Plugin for our intranet.

Main goal: The Confluence blueprint "Share a link" should create blog posts and no pages. We want to add your Macro in the Blueprint Editor and then we hope, that new pages from that blueprint will automatically be put to the Blog posts.

The problem is that the macro (as commented in the other issue) actually does not work for any template so that we cannot test the behavior for blueprints.

Can you confirm that the macro will work for blueprints as well, so that we can purchase your Plugin next week together with some other plugins (easier for the internal order workflow).

Thanks a lot,
Jan

**Comment by chris-kent** [comment]
Please install version 3.16, I believe this has now fixed the issue
