### ISSUE TITLE
In Need of noticifation for the watchers after conversion

### ISSUE THREAD

**Issue by lisazi** [chris-kent/Confluence-Blog-Tools#34]
Hi dear Support Team,

we are in need of a notification about the conversion of a page in a blog or the other way around.
Therefore its important that the watchers of a page or blog will not be deleted by the conversion due to your add-on.

Is this possible to implement?
Can you tell me in which time frame you are able to implement this in the next update of your addon?

looking forward to hear from you!

regards,

Lisa Zimmer

**Comment by chris-kent** [comment]
Hi Lisa,

I am currently working on improving the "Page to Blog" macro for the blog
template as this has been hampered by a recent redesign by Atlassian, so I
have to redesign my plugin.
Once this work is completed, I can add the notification to watches.

I would like to have this done by the end of the month.

Cheers

**Comment by lisazi** [comment]
Hi Chris,

can you make a guess at what earliest moment you can publish the new update of blog tools?

thanks for your help!
looking forward to hear from you!

regards,

Lisa Zimmer

**Comment by chris-kent** [comment]
Please install version 3.16, I believe this has now fixed the issue
