### ISSUE TITLE
Published blogs are restricted from all but creator

### ISSUE THREAD

**Issue by jfsat** [chris-kent/Confluence-Blog-Tools#35]
We've had a few instances of people trying to use a template to publish blogs, but when they publish their pages, the new page (blog) is restricted to only their viewing. This happened yesterday most recently, and I was able to grab the logs for what happened. This only seems to happen to people who don't have space admin, although it might also be a restriction permission. Not sure, but I'm lead to believe that it's an admin issue because the logs are talking about purging trash.
[Blog publish problem.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/2189846/Blog.publish.problem.txt)

**Comment by chris-kent** [comment]
Hi,

This is a known problem and I am redesigning the blog template
functionality to fix this issue.

Cheers
Chris

**Comment by chris-kent** [comment]
Please install version 3.16, I believe this has now fixed the issue
