### ISSUE TITLE
Impossible to specify a parent page

### ISSUE THREAD

**Issue by corvis84** [chris-kent/Confluence-Blog-Tools#39]
When I'm trying to convert a blog post to a page, I'm supposed to choose a parent page but nothing is found and wheel keeps going ...

**Comment by chris-kent** [comment]
Hi there,

I need more information to help you, can you please add further information
using the tips on this page:
https://kcintegrations.atlassian.net/wiki/spaces/PLUG/pages/187269133/Service+Level+Agreement

Thanks
Chris
