### ISSUE TITLE
When converting a page to a blog-entry Access-Restrictions are lost

### ISSUE THREAD

**Issue by heiglandreas** [chris-kent/Confluence-Blog-Tools#4]
When you convert a page to a blog-entry the access-restrictions set for the page are lost. Our use case is as follows:
* A user creates a new page based on a template that contains the "page-to-blog"-macro. 
* The user restricts viewing to herself to be able to finish off the article without others seeing it already.
* On first saving the page the page gets converted to a blog-entry but the restrictions are lost. Therefore all users can see the article even though it is not yet ready for viewing!

Any chance to get that fixed? We are currently using BlogTools 2.4 in Confluence 5.8.9

Update: The issue also arrises when converting a simple page with restrictions to a blog-post. All Restrictions are lost.

**Comment by chris-kent** [comment]
Hi

Thank you for your feedback. That is an excellent use case that I have not thought of before (obviously).

I will impliment this and issue a new version. Please look out for it over the next few days. I am currently focused on another plugin which I hope to release today.

Cheers
Chris




Sent on the go with Vodafone


-------- Original message --------

**Comment by heiglandreas** [comment]
It looks like the same is happening for tags. They can be added while you edit a page and on converting the page to a blog-post they are lost...

**Comment by chris-kent** [comment]
Hi Andreas,

Thanks for the information.  I will look at this issue this week and hope to have an update for you soon.

Thanks
Chris

**Comment by heiglandreas** [comment]
I'Ve investigated further with the updated plugin (preservation of restrictions works great! Thanks!). It looks like the tags from the template are preserved but the tags that were added while editing the *page* are lost on conversion to a blog-entry...

Does that help somehow?

**Comment by chris-kent** [comment]
Hi,

Yes that does. I am now free of other commitments so I should be able to have a fix to you soon.

Cheers
Chris



Sent on the go with Vodafone


-------- Original message --------

**Comment by chris-kent** [comment]
Hi Andreas,

This has been fixed and a new version 2.6 is available to download.

Cheers
Chris

**Comment by heiglandreas** [comment]
Hi Chris.

Great! Works like a Charm! Thanks for the great plugin and the even greater support :wink:!

**Comment by chris-kent** [comment]
Hi Andreas,

Glad I can help you.  If you don't mind, would you mind reviewing my plugin on the Market place. I don't have any yet and I would really appreciate a kind word from a user.

Thanks
Chris

**Comment by chris-kent** [comment]
That was fast. Thank you for the kind words. 

Cheers
Chris

P.s if you have any suggestions to improve this plugin please raise another issue. 

I am also activity looking for other plugins to create, so if confluence is missing any other features please let me know
