### ISSUE TITLE
Images in comments by disabled users are lost after conversion

### ISSUE THREAD

**Issue by pflan** [chris-kent/Confluence-Blog-Tools#40]
After converting a page into a blog post, images in comments posted by disabled users are lost.

**Comment by pflan** [comment]
(I should say that because this only impacts disabled users, it's annoying and surprising, but it's usually not that bad. The text of the comment is preserved, and in our usage, usually the image is just supplemental, not crucial.)

**Comment by chris-kent** [comment]
Hi 
I was unable to replicate this problem, does it still occur?
If so, I will need to add additional logging so that I can try to delve deeper into this and ask you to run it on your server.
If you want this to happen, please let me know.
Cheers
Chris

**Comment by pflan** [comment]
I was actually only able to find one example in our installation, and when I migrated the page, I lost the image. I could try to recover it from a backup and see if I can reproduce, but given that it's so infrequent (only one occurrence, and now zero), I'm not worried about it.

**Comment by chris-kent** [comment]
This is unavoidable, as detailed in the documentation
