### ISSUE TITLE
Email Notification does not work after converting page to blog

### ISSUE THREAD

**Issue by Trexon25** [chris-kent/Confluence-Blog-Tools#46]
**Describe the bug**
When I create first a page and then convert it to a blog no email notification will be sent to the watchers.

**To Reproduce**
1. Go to the blog section
2. create a page
3. convert the page to a blog
4. no email notification

**Expected behavior**
Email should be sent to the watchers

**Screenshots**
-

**Versions (please complete the following information):**
 - Confluence: tested on 7.4.1 and 6.13.0
 - Plugin: Blog, Page and Template Tools
 - Data Center: Not Supported

**Comment by chris-kent** [comment]
Hi Beat,

The behaviour you have described is not a bug but a design decision. Email
notifications are disabled for all transitions between Pages and Blogs.

This came about in the early days of the App development, and customers did
not want notifications since the content doesn't actually change, just the
location. So this was added into the implementation.

I hope this helps with your understanding.

Cheers
Chris
KC Integrations

**Comment by Trexon25** [comment]
Hi Chris

Thanks for your fast response, I get it what you mean. 
The problem we have is that you can't schedule a blog for the future, so we thought we will use pages as blog templates and when an employee wants to release the blog he can just convert it to a blog. We are using Confluence with 2000 users. 

Is there maybe a way we can enable it, or a easy implementation?

Thanks and Kind Regards
Beat

**Comment by chris-kent** [comment]
Hi Beat

Yes it would be fairly easy for me to add a flag on the form before
conversion to "send notifications".

Would this  work for you?

Cheers
Chris

**Comment by Trexon25** [comment]
Hi Chris

Yes that would work for us. 

Many thanks in advance for the implementation.

Kind Regards
Beat

**Comment by chris-kent** [comment]
Hi Beat,

This has been done for you, please download the latest version from the
Marketplace.

Cheers
Chris

**Comment by Trexon25** [comment]
Hi Chris

Thanks for the implementation. I updated the app on our test system and I now can enable the checkbox for sending emails. Unfortunately email notification does not work. I disabled all Email notifications in my account (normal blog creation I will receive an email) do I have to enable any of the email notification options?

![Confluence-Mail-Settings](https://user-images.githubusercontent.com/35470572/87956710-a2f0d080-caaf-11ea-8e1c-cbeff265fdca.png)


Thanks & Kind Regards
Beat

**Comment by chris-kent** [comment]
Hi Beat,

The only way users get notified when new content is created, is if they are
watching the space.
They also only get notified of modified content if they are watching the
space or the page/blog.

This notification mechanism you asked for is only for "watches", it has
nothing to do with the subscription Email setting you provided.

Are you watching the Page that you are converting? Are you watching the
Space that this content is in?

Can you verify who is watching the content, and that they are still
watching the content once it has been converted? Also test with users who
are watching the space.

Cheers
Chris

**Comment by Trexon25** [comment]
Hello Chris

I tested the following things:

1) watching the complete space:
    - Email received when creating a new page
    - Email received when creating a new blog
    - Email **not** received when converting a page to a blog
    - Email **not** received when editing the page
    - Email **not** received when editing the blog

2) watch a single page
    - Email **not** received when editing the page
    - Email **not** received when converting the page to a blog
    - Email **not** received when editing the blog

When watching only one page, after converting it to a blog I'm still watching it.

I've tested it with two accounts (one is watching and with the other account I did the changes).

Is there maybe a log file from the plugin I can check if it should work?

Thanks and Kind Regards
Beat

**Comment by chris-kent** [comment]
Hi Beat,

I'm not sure why you are not getting emails from standard page/blog edits.
I'm guessing this is the reason why you are not getting emails from the
conversion. If you fix the Confluence setting that is preventing emails
from normal page edits (nothing to do with my plugin, but I utilise this
mechanism), then hopefully emails will work. Looking at the email settings
you showed me earlier, you have page edit notification turned off, if this
is still the case then maybe turn them back on...

Let me know how it goes.

Cheers
Chris

**Comment by Trexon25** [comment]
Hi Chris

I've tested a lot of things and I found that we have some custom JavaScript code that will uncheck the checkbox "Notify Watchers".
![image](https://user-images.githubusercontent.com/35470572/91301880-e7097c00-e7a5-11ea-8a1b-cdbd9b8d65b5.png) After I checked the checkbox normal page/blog edit notifications worked. Unfortunately notifications from converting a page to a blog not. I also tried to remove completely our custom JavaScript code. Also the mail settings in the profile does not have any impact on the notifications. Do you have any idea why it is still not working?

Thanks & Kind Regards
Beat

**Comment by chris-kent** [comment]
[confluence-blog-tools-4.4.zip](https://github.com/chris-kent/Confluence-Blog-Tools/files/5167937/confluence-blog-tools-4.4.zip)
Hi Beat,
Try this version and let me know if this sends email notifications. To install this file, replace .zip with .jar and upload it to your server.
Cheers
Chris

**Comment by Trexon25** [comment]
Hi Chris

Are there any news?

Kind Regards
Beat
