### ISSUE TITLE
Data Center Compatibility?

### ISSUE THREAD

**Issue by plabarbera** [chris-kent/Confluence-Blog-Tools#5]
Hi there,

I'm building a Confluence-based intranet for American Express. They're on a 10k user Data Center license... and I reallllly want this plugin.

They refuse to install it in production unless it's Data Center compatible. Do you have a schedule or a plan to note this as Data Center compatible on the Atlassian marketplace?

**Comment by chris-kent** [comment]
Hi there,

This is my first Data Center request. I don't believe I should have any issues adding this compatibility as my plugin does not cache any data.

What I do need to do is setup a test system and validate that my plugin meets the Data Center requirements.

I will endeavor to have an update for you soon.

Cheers
Chris

**Comment by chris-kent** [comment]
Hi There,

I have done compatibility testing for Data Center and all passed, so I have added Data Center compatibility to the plugin.

You are now fine to install.

Cheers
Chris
