### ISSUE TITLE
"Convert Page to Blog Post" action deletes the metadata set of a page

### ISSUE THREAD

**Issue by maximilianpeter** [chris-kent/Confluence-Blog-Tools#7]
Hi,
we are using the metadata plugin (https://marketplace.atlassian.com/plugins/com.communardo.confluence.metadata/server/overview) to set metadata information for a page or blog post. Additionally we are using the "Confluence-Blog-Tools" to create a blog post within a template or by using the "Convert Page to Blog"-action.

When we convert a page into a blog post, unfortunately the metadata information from the page are not copied to the blog post. This is a problem for our use case with Metadata and Confluence Blog Tools Add-on. May you help us?
Greets Max

**Comment by chris-kent** [comment]
Hi Max,

Thanks for your feedback, I will have a look at this issue and get a fix
for it soon. Although, I should not be removing any macros from templates,
so I will need to install metadata plugin and see how it behaves in
templates and pages. (Actually do you use the metadata plugin in templates,
or do I only need to look at my Conversion functions?)

At the moment I am trying to get this plugin compatible with the latest
5.10.0 version which has some changes that drastically affect my code, once
this is resolved I'll get back to your issue above.

On another note, I saw your request for adding permissions to standard
templates. I believe I can do that too in my plugin. I was thinking of
adding a new macro that accepts page permissions and then applies those
when the page is created for the first time.  Would that suit your
scenario?  If so I'll work on that after the above 2 issues are sorted.

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,

thanks for your answer! Actually we are using metadata plugin in templates. But in future it is also an option to use the conversation function (Convert Page to Blog) within metadata. 

The new option for adding permissions to standard templates sounds very interesting. That could be a nice feature for us, but not with a high priority. 

Do you have a timeplan for fixing the first bug?

Greets Max

**Comment by chris-kent** [comment]
I am working now on confluence 5.10.0 support, this may take a few nights
to achieve.

As for integrating with metadata plugin, I have reached out to the
developer for his API so I can get the data, however he has not responded.
So this work will be dependent on what support I get from Communardo
Software GmbH <https://marketplace.atlassian.com/vendors/95>.

Maybe you could reach out to them as a customer and ask for support, then
they might help me.  My out of the blue request for their API might seem
like I am wanting to plagiarize their solution.

I will help if I can, but I need their API.

Thanks
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,
I asked them for support and they told me, that they might get in touch with you.
Greets Max

**Comment by maximilianpeter** [comment]
Hi Chris, 
did you get any informations you need?
Greets
Max

**Comment by chris-kent** [comment]
Hi

I did get the reference I need.

I am still not compatible with 5.10.0. Which confluence version are you on.
I am thinking I will swap priorities and fix your request first, then get
back to 5.10 support.

Will this suit you?

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hi Chris,
this would be very nice, because we have a high priority use case for this request.
Greets Max

**Comment by chris-kent** [comment]
Hi Max,

I have added support but I have not tested. I don't have the time to learn
the metadata plugin and setup any meta data.
So, if you don't mind, can you please try this beta version and see if it
works?

I believe this will only work if the MetaData plugin is installed, without
it, my plugin fails, which happens on my test because I don't have the
metadata plugin.  So this beta version is only good for you...

To install, download the attachment, add .jar to the filename, and manually
install the plugin.  If this does not work, then you can re-install version
2.9 from the marketplace and then let me know.

Thanks
Chris

**Comment by maximilianpeter** [comment]
Hello Chris,

thank you very much. I'm going to try it, but there is no attachement at your post.

Greets Max

**Comment by chris-kent** [comment]
Hi Max,

Wondering if this worked for you?

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hey Chris, I can't find the attachment with the new version. Greets max

**Comment by chris-kent** [comment]
Oh, try this... rename it from .zip to .jar...

and follow the instructions I sent through earlier.

Cheers
Chris 
[confluence-blog-tools-2.10.1.zip](https://github.com/chris-kent/Confluence-Blog-Tools/files/346141/confluence-blog-tools-2.10.1.zip)

**Comment by maximilianpeter** [comment]
Hello Chris,
this version doesn't work. We tried to install it, but we get an error message: "This add-on couldn't be activated". Here is the error log as attachement.

Greets Max 
[error_blogtools.txt](https://github.com/chris-kent/Confluence-Blog-Tools/files/349396/error_blogtools.txt)

**Comment by chris-kent** [comment]
Hi there,

What version of Confluence do you have?

Chris

**Comment by maximilianpeter** [comment]
Hi Chris,

we are currently on version 5.8.15.

Greets max

**Comment by chris-kent** [comment]
Hi Max,

Sorry for the absence, having so many issues with Confluence 5.10.0 and
Atlassian are slow to assist.
I have reverted a lot of changes, back to my last working plugin on the
marketplace.
From here I have added metadata support, I think, I have not been able to
test as my environment does not allow me to install plugins from market
place.

So, please try the attached version again and let me know if this works.

Cheers
Chris.

**Comment by maximilianpeter** [comment]
Hi Chris,

thank you very much. There is no new file attached at your post. Which version should I install?

Greets Max

**Comment by chris-kent** [comment]
Ah, got caught by replaying via email and not using github for attachments.... see attached
[confluence-blog-tools-2.10.1.zip](https://github.com/chris-kent/Confluence-Blog-Tools/files/368557/confluence-blog-tools-2.10.1.zip)

**Comment by maximilianpeter** [comment]
Unfortunately it doesn't work. When we convert a page into a blog post the metadata information from the page are not copied to the blog post. There ist the same problem with the "Page to Blog" macro.

**Comment by chris-kent** [comment]
Hi Max,

Can you please confirm...

1. The "Convert Page to Blog" menu action does not work.
2. The macro used in "Page to Blog" in space templates does in fact work.

Is this correct?

**Comment by maximilianpeter** [comment]
Hi Chris,

both of them work as well but when I use the macro or the menu action, the metadata-values aren't copied to the blog-post.

Greets Max

**Comment by chris-kent** [comment]
Hi Max,
Try this version, I have added a lot of logging code to understand what might be happening. Can you please try the following
1. Install attached version
2. Turn on logging , goto Admin->Loggin and Profiling -> Add entry for "net.kentcom" ALL.
3. Convert a Page either use the template or tool.
4. Grab your Confluence log file, and grep all the lines that have [net.kentcom] and send to me.

Hopefully this will help.  

Chris
[confluence-blog-tools-2.10.1.zip](https://github.com/chris-kent/Confluence-Blog-Tools/files/369003/confluence-blog-tools-2.10.1.zip)

**Comment by maximilianpeter** [comment]
Hi Chris,

I have tried the actions and received a log file.
Greets max

**Comment by maximilianpeter** [comment]
Hi Chris,

is this logfile helpful for you?

Greets Max

**Comment by chris-kent** [comment]
Hi Max,

Unfortunately not. I have been banging my head against a wall trying to get
this to work. Finally I have reached out to metadata developers again with
error logs relating to their API integration.

Hopefully they will come back with something I can try this week.

Sorry for the lengthy delay, but I do  hope to get this working - sometime.

Cheers
Chris.

**Comment by chris-kent** [comment]
Hi Max,

The developers have helped me get a little further. Apparently I am the first to use their API.
Anyway, I have tried to test this, however when I enable the metadata plugin I can no longer edit pages, so it makes it a little hard to test.  But I have a good feeling it will work.

Can you please give this a try and let me know how it goes. If it does not work, enable logging again and send through the log file.

Cheers
Chris
[confluence-blog-tools-2.10.1.zip](https://github.com/chris-kent/Confluence-Blog-Tools/files/401658/confluence-blog-tools-2.10.1.zip)

**Comment by maximilianpeter** [comment]
Hi Chris,
this works fine. Thank you very much for your great service! Looking forward for the 5.10 support. Good luck for you. 

Greets Max

**Comment by chris-kent** [comment]
Hi Max,

Now that you ave this working, there are a few issues.
1. It only works with MetaData plugin Enabled.
2. You will not be able to get new versions from Market place until I fix
the above.

I will let you know when I have done point 2 above.

Until then, you will be able to use the 2.10.1 version until you migrate to
Confluence 5.10.  At which stage I hope they have fixed a bug which is
preventing me from providing compatibility.

It would help if you voted for this bug to be fixed, please see
https://jira.atlassian.com/browse/CONF-43323

Cheers
Chris

**Comment by maximilianpeter** [comment]
Hey Chris, 

thanks for the information. I have already voted for this issue. Hope Atlassian will Support you.

Greets max

**Comment by maximilianpeter** [comment]
Hey Chris,

what's about point 2 in the above message? Is it already fixed?

Greets Max

**Comment by chris-kent** [comment]
Hi Max,
Sorry, yes this was done and is now in the latest MarketPlace listed version.
You can upgrade now and I hope it works for you.

Cheers
Chris

**Comment by chris-kent** [comment]
Available since 3.2

**Comment by maximilianpeter** [comment]
Hi Chris, we updatet to 3.4 with Confluence 5.10.8 and have the same issue again: 

> When we convert a page into a blog post, unfortunately the metadata information from the page are not copied to the blog post.

Unfortunately we have another problem with the Blog Post Macro. When we create a page by using the confluence macro "Create page from template" and the template has the Blog Post Macro on it, the new site is still created as a childpage not as a blog-post.

Greets Max

**Comment by maximilianpeter** [comment]
Don't know how to open the issue again. Hope it's OK to comment it.
