### ISSUE TITLE
Confluence 5.10.0

### ISSUE THREAD

**Issue by moondog13** [chris-kent/Confluence-Blog-Tools#8]
We've been loving this plugin as it has saved us a ton of time! We recently had an issue where we needed to upgrade confluence to 5.10.0 but we cannot yet get your plugin installed. I'm curious if we can contribute to the efforts of getting your plugin ready for this version. Would a little paypal or bitcoin action help your timeline?

**Comment by chris-kent** [comment]
Hi there,

That was funny, extra donations won't help.  I am actually struggling with
Atlassian's development environment with 5.10.0.  Mine breaks whenever I
use this version - fine for all previous versions. I have been researching
for the last week on how to overcome this but looks like I am the only one
who has this problem

I am now setting up a brand new 5.10.0 full production install and I will
then be able to test my plugin against this.

I hope to be able to release a compatible version early next week.

Thanks for your patience.

There will also be a few new features coming soon too :)

Cheers
Chris

**Comment by rhodessteve** [comment]
This is the only plugin thats not been updated to 5.10 in our list of 15 or so plugins. We would like to update the test environment which should fix a whole bunch of problems we've had with 5.9.

**Comment by chris-kent** [comment]
Hi There,

I am currently working on this.

I appreciate your patience and hope to resolve compatibility issues soon.

Cheers
Chris

**Comment by erindelaneyb** [comment]
Chris, 

Any luck so far? This add-on is pretty essential for us and we are holding off on upgrading to 5.10 until it's operational.

**Comment by chris-kent** [comment]
Hi,

Unfortunately there is a bug in Confluence that prevents my template macro from working. I have raised a trouble ticket and now waiting for Atlassian to fix it.

If you are happy to use the 2 conversion tools, from the Page menu, these still work (**Convert Page to Blog** and **Convert Blog to Page**). If this is all you need, my 2.9 version will install and run in Confluence 5.10, you just have to manually install the plugin (ie. download from market place and upload it manually.) 

It will say that it is not compatible, but the 2 conversion functions above work.

Hope this helps and that Atlassian fix their bug soon.

Chris

**Comment by erindelaneyb** [comment]
Chris, 

Thanks for the prompt reply and for clarifying so well what's going on. Really appreciate it. I hope Atlassian responds to you. We badly need the template macro, and look forward to it working again.

**Comment by erindelaneyb** [comment]
Chris, 

Sorry to bother you -- if your ticket with Atlassian is public, I would love to be provided with a link so we could watch/vote for the issue if possible.

**Comment by chris-kent** [comment]
Hi There,

That would be a great idea, I'm getting very frustrated with the lack of
support about this, basically they have broken my plugin.

https://jira.atlassian.com/browse/CONF-43323

Cheers
Chris

**Comment by moondog13** [comment]
I've added my vote and watch to it. I see the priority is set as minor.
As this issue is critical for your plugin are you able to adjust it's
priority? I'm hoping the priority wasn't downgraded after submission. Is
it of any benefit for us to add comments to the ticket or is that just
needless clutter? Also, is it worth submitting a severe support request
from our confluence instances citing CONF-43323
<https://jira.atlassian.com/browse/CONF-43323> as the block?

**Comment by erindelaneyb** [comment]
Chris -- 

Just wanted to make sure you saw that [your ticket](https://jira.atlassian.com/browse/CONF-43323) has been marked as resolved!

**Comment by chris-kent** [comment]
Fixed in Version 3.4
